import type { Metadata } from "next";
import { Inter, Merriweather } from "next/font/google"
import "./globals.css";
import {Navbar} from '@/components/Navbar'
import {Footer} from '@/components/Footer'

const interSans = Inter({
  variable: "--font-inter"
})

const merriweather = Merriweather({
  variable: "--font-merri"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${interSans.variable} ${merriweather.variable} antialiased bg-[url('/images/asphalt.png')] bg-repeat text-white w-screen min-h-screen m-0 p-0`}>        
        <div className="max-w-[1600px] mx-auto p-4">
          <Navbar />
        </div>
        {children}
        <div className="bg-black">
          <Footer />
        </div>
      </body>
    </html>
  );
}
